services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - ADMIN_PASSWORD=kalsierk
      - ADMIN_NAME=karlod1130
      - URLMONGO=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/chat?replicaSet=rs0
      - URL=mongodb://25.5.195.42:27017/chat?replicaSet=rs0
    networks:
      - chat-net

  frontend:
    build:
      context: .
      dockerfile: public/Dockerfile.fe
    ports:
      - "80:80"
    networks:
      - chat-net

  sync:
    build: 
      context: .
      dockerfile: sync/Dockerfile.sy
    container_name: sync
    environment:
      - URL_MONGO=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/chat?replicaSet=rs0
      - URL=mongodb://25.5.195.42:27017/chat?replicaSet=rs0
      - NODE_ID=node1
      - ADMIN_PASSWORD=kalsierk
      - ADMIN_NAME=karlod1130
    ports:
      - "4000:4000"
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge
